### ISSUE TITLE
Change antibody names to AZD names

### ISSUE THREAD

**Issue by ajgreaney** [jbloomlab/SARS-CoV-2-RBD_MAP_AZ_Abs#7]
@jbloom I don't have permission to edit the "About" section of this repo. Would you be able to please change the "About" section to read "Mutational antigenic profiling of AZD8895 and AZD1061" (removing the 2196 and 2130 names). This will update the landing page for the stable dms-view link. See here:

<img width="1025" alt="Screen Shot 2021-05-19 at 11 48 50 AM" src="https://user-images.githubusercontent.com/28786335/118867230-b28ba200-b897-11eb-978b-66d98d042049.png">

**Comment by jbloom** [comment]
I think I did this. Let me know if it didn't work.

**Comment by ajgreaney** [comment]
It did work on repo "About" section but it hasn't changed or updated here: https://jbloomlab.github.io/SARS-CoV-2-RBD_MAP_AZ_Abs/

I couldn't find any other likely candidate for where this text was being derived from, so I'm not quite sure how to update this page then.

**Comment by ajgreaney** [comment]
Oh @jbloom I think you might need to turn off GitHub pages and then turn them back on. This should be under `Settings` but I also don't have permission to see or edit Settings.

**Comment by jbloom** [comment]
OK, check again. (I did the turn off / on).
